from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon6.jpg'

# COLOR
PRIMARY_COLOR = '#FF1202'
DARKER_PRIMARY_COLOR = '#A80505'
DARKEST_PRIMARY_COLOR = '#780303'


# Sizing
BIG_FONT_SIZE = 20
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 400
